name: NASA CMAPSS FD001
format: txt
sampling_type: cycles
signal_columns:
  - s1
  - s2
  - s3
  - s4
  - s5
  - s6
  - s7
  - s8
  - s9
  - s10
  - s11
  - s12
  - s13
  - s14
  - s15
  - s16
  - s17
  - s18
  - s19
  - s20
  - s21
meta_columns:
  - unit_id
  - cycle
  - op1
  - op2
  - op3
task: rul
label_column: null
label_from_filename: false